### ISSUE TITLE
Extracting Priors (BUGSModel)

### ISSUE THREAD

**Issue by serenlee** [TuringLang/JuliaBUGS.jl#241]
Hi, I am new to JuliaBUGS and have a quick question about extracting priors.
I can find there is code for sampling from prior distributions if initialization values are not specified, but other than this, is there any way to extract the BUGSModel of priors? - which is similar to DynamicPPL.PriorContext().

**Comment by sunxd3** [comment]
Hi @serenlee, thanks for the question.

There is indeed a function that sample from the prior,
```julia
julia> using JuliaBUGS, Random

julia> (; model_def, data) = JuliaBUGS.BUGSExamples.pumps;

julia> model = compile(model_def, data);

julia> values, logp = JuliaBUGS.evaluate!!(Random.default_rng(), model);

julia> new_model = JuliaBUGS.BangBang.setproperty!!(model, :evaluation_env, values);

julia> JuliaBUGS.getparams(new_model) # return a vector of parameter values in transformed space
12-element Vector{Float64}:
 -3.10825293209275
  0.8447929064727833
 -1.417527029046425
  8.949624694711742
  2.69358020133434
  6.712659628025856
  7.056276437025096
  1.6044102202504353
  2.1440248535550643
 -1.0053144826150906
 -2.2399832098899113
  8.068518491045396

julia> JuliaBUGS.getparams(JuliaBUGS.OrderedDict, new_model)
OrderedCollections.OrderedDict{Any, Any} with 12 entries:
  beta      => -3.10825
  alpha     => 0.844793
  theta[10] => -1.41753
  theta[9]  => 8.94962
  theta[8]  => 2.69358
  theta[7]  => 6.71266
  theta[6]  => 7.05628
  theta[5]  => 1.60441
  theta[4]  => 2.14402
  theta[3]  => -1.00531
  theta[2]  => -2.23998
  theta[1]  => 8.06852
```

But the interface is very crude at the moment and yet still might change in near future. I am eager for feedbacks on making it better, so please let me know your use case and I can quick addition or adjustment. Also, very happy to clarify any confusions. 

And just for some extra information, DynamicPPL's `PriorContext` is used to specify that the logp returned is the logprior, while sampling is specified using `SamplingContext`.

```julia
julia> model = DynamicPPL.TestUtils.DEMO_MODELS[1]; # using one of the test models

julia> vi = VarInfo(model);

julia> DynamicPPL.evaluate!!(model, vi, SamplingContext(DefaultContext()))[1]
(s = [0.8851022821211684, 4.077537995917044], m = [1.4249711457430558, -3.5314199609314683], x = [1.5, 2.0], logp = -14.971564651125178)

julia> DynamicPPL.evaluate!!(model, vi, SamplingContext(PriorContext()))[1]
(s = [0.8851022821211684, 4.077537995917044], m = [1.4249711457430558, -3.5314199609314683], x = [1.5, 2.0], logp = -8.73693873589652)

julia> DynamicPPL.evaluate!!(model, vi, SamplingContext(LikelihoodContext()))[1]
(s = [0.8851022821211684, 4.077537995917044], m = [1.4249711457430558, -3.5314199609314683], x = [1.5, 2.0], logp = -6.2346259152286585)
```

**Comment by serenlee** [comment]
Thank you for your response @sunxd3 

It works well for me. 
I should have clarified my question. I mixed two things - actually, it would be nice if I could have two things - 1. sampling from priors (which is resolved as in your comment) and 2. evaluating in prior context (logp).

AbstractPPL.evaluate!!(model::BUGSModel, flattened_values::AbstractVector)
  can return logp, but is there anything for the prior model?

**Comment by sunxd3** [comment]
I am absolutely happy to add something. 

So something can be easily add is for
```julia
AbstractPPL.evaluate!!(model::BUGSModel, flattened_values::AbstractVector)
```
and
```julia
AbstractPPL.evaluate!!(rng, model::BUGSModel)
```
to not just return a log joint (`logp`), but also log prior and loglikelihood. Is this what you mean by

> 2. evaluating in prior context (logp)

?

**Comment by serenlee** [comment]
Thank you for your help.

And yes, so, given vector as flattend_values,
something similar to `AbstractPPL.evaluate!!(model::BUGSModel, flattened_values::AbstractVector)`
but return log prior density values at flattend_values (either together with log joint or log prior alone. Both are fine).
